---
- name: Converge
  hosts: all
  become: true

  vars:
    # Role: rhsm
    rhsm_username: "{{ lookup('env', 'RHSM_USERNAME') }}"
    rhsm_password: "{{ lookup('env', 'RHSM_PASSWORD') }}"
    rhsm_auto_attach: true
    rhsm_server_proxy_hostname: "{{ lookup('env', 'http_proxy_hostname') }}"
    rhsm_server_proxy_port: "{{ lookup('env', 'http_proxy_port') }}"
    rhsm_server_proxy_user: "{{ lookup('env', 'http_proxy_user') }}"
    rhsm_server_proxy_password: "{{ lookup('env', 'http_proxy_password') }}"
    rhsm_consumer_name: "nycrecords_{{ '%Y%m%d_%H%M%s' | strftime(ansible_date_time.epoch) }}"

    # Role: java
    java_home: /usr/lib/jvm/jre-1.8.0-openjdk

    # Role: Solr
    solr_version: 7.7.2
    solr_remove_cruft: true
    solr_xms: "128M"
    solr_xmx: "128M"
    solr_timezone: "GMT-5"

    solr_core_config_git: true
    solr_cores:
      - name: hyrax
        git_repo: https://github.com/nycrecords/gpp-hyrax.git
        sparse_checkout:
          - solr/config
      - name: test
        git_repo: https://github.com/nycrecords/gpp-hyrax.git
        sparse_checkout:
          - solr/config

  roles:
    - role: nycrecords.rhsm
    - role: nycrecords.java
    - role: ansible-role-solr
